api/urls.py
# from django.urls import path, include
# from .views import ProductoList, ProductoDetalle, \
#     ClienteList

# urlpatterns = [
#     path('v1/productos/',ProductoList.as_view(),name='producto_list'),
#     path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
#     path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
# ]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import *

app_name = "config"

urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='bases/login.html'),
         name='logout'),
    
    path('users/lists',UserList.as_view(),name="users_list"),
    path('users/add',user_admin,name="user_add"),
    path('users/modify/<int:pk>',user_admin,name="user_modify"),
    path('users/groups/list',UserGroupList.as_view(),name="user_groups_list"),
    path('users/groups/add',user_groups_admin,name="user_groups_new"),
    path('users/groups/modify/<int:pk>',user_groups_admin,name="user_groups_modify"),
    path('users/groups/delete/<int:pk>',user_group_delete,name="user_groups_delete"),
    
    path('users/groups/permission/<int:id_grp>/<int:id_perm>',user_group_permission,name="user_groups_permission"),
    path('users/groups/admin/<int:id_usr>/<int:id_grp>',user_group_add, \
        name="user_groups_admin"),

    # path('catalogos/categorias',
	#  Home.as_view(),
	#  name='categorias'),
    # path('catalogos/subcategorias',
    #     Home.as_view(),
    #     name='subcategorias'),
    # path('movimientos/compras',
    #     Home.as_view(),
    #     name='compras'),
]

partido politico/api/urls.py
# from django.urls import path, include
# from .views import ProductoList, ProductoDetalle, \
#     ClienteList

# urlpatterns = [
#     path('v1/productos/',ProductoList.as_view(),name='producto_list'),
#     path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
#     path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
# ]

partido politico/inv/urls.py
from django.urls import path

from .views import get_person_data ,\
    inscripcion , lista_inscritos

app_name = "inv"

urlpatterns = [
    path("inscripcion", inscripcion , name = "inscripcion"),
    path("lista_inscritos", lista_inscritos , name= "lista_inscritos"),
    path('get_person_data/', get_person_data, name='get_person_data'),


]

proyecto/urls.py
from fichas import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('inscripcion/', views.inscripcion, name='inscripcion'),
    path('get_person_data/', views.get_person_data, name='get_person_data'),
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('fichas/',include(('fichas.urls','fichas'), namespace='fichas')),
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
]

partido politico/api/models.py
from django.db import models

# Create your models here.

partido politico/bases/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.db import models
from django.forms import fields
from django import forms
from django.forms.widgets import PasswordInput

from .models import Usuario

class UsuarioCreationForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioCreationForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = ("email",)


class UsuarioChangeForm(UserChangeForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioChangeForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = '__all__'

class Userform(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput)
    
    class Meta:
        model = Usuario
        fields = ['email','first_name','last_name','password']
        widget = {'email': forms.EmailInput,
                   'password': forms.PasswordInput }

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

partido politico/inv/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget
from .models import FichaInscripcion

class FichaInscripcionForm(forms.ModelForm):
    referido_por = forms.ModelChoiceField(
    queryset=FichaInscripcion.objects.all(),
    required=False,
    widget=forms.Select(attrs={'class': 'form-control'})
)

    class Meta:
        model = FichaInscripcion
        fields = [
            'dni', 'nombres', 'apellido_paterno', 'apellido_materno', 'fecha_nacimiento', 'referido_por',
            'lugar_nacimiento', 'telefono_fijo', 'celular', 'email', 'sexo', 'estado_civil',
            'grado_instruccion', 'profesion', 'direccion', 'distrito', 'provincia', 
            'departamento', 'centro_laboral', 'cargo_laboral', 'direccion_laboral',
            'distrito_laboral', 'provincia_laboral', 'departamento_laboral',
        ]
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
            'dni': forms.TextInput(attrs={'id': 'dni', 'maxlength': '8'}),
            'sexo': forms.RadioSelect(),
            'estado_civil': forms.Select(),
            'grado_instruccion': forms.Select(),
            'email': forms.EmailInput(attrs={'type': 'email'}),
            'celular': forms.TextInput(attrs={'type': 'tel'}),
            'telefono_fijo': forms.TextInput(attrs={'type': 'tel'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if not isinstance(self.fields[field].widget, (forms.RadioSelect, forms.CheckboxSelectMultiple)):
                self.fields[field].widget.attrs.update({'class': 'form-control'})

    def clean_dni(self):
        dni = self.cleaned_data.get('dni')
        if not dni.isdigit() or len(dni) != 8:
            raise forms.ValidationError("El DNI debe ser un número de 8 dígitos.")
        return dni

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if FichaInscripcion.objects.filter(email=email).exists():
            raise forms.ValidationError("Este email ya está registrado.")
        return email

    def clean_celular(self):
        celular = self.cleaned_data.get('celular')
        if not celular.isdigit() or len(celular) != 9:
            raise forms.ValidationError("El número de celular debe tener 9 dígitos.")
        return celular

partido politico/api/views.py
# from django.shortcuts import render

# from rest_framework.views import APIView
# from rest_framework.response import Response
# from django.shortcuts import get_object_or_404

# # from .serializers import ProductoSerializer, ClienteSerializer
# # from inv.models import Producto
# # # from fac.models import Cliente

# from django.db.models import Q

# class ProductoList(APIView):
#     def get(self,request):
#         prod = Producto.objects.all()
#         data = ProductoSerializer(prod,many=True).data
#         return Response(data)

# class ProductoDetalle(APIView):
#     def get(self,request, codigo):
#         prod = get_object_or_404(Producto,Q(codigo=codigo)|Q(codigo_barra=codigo))
#         data = ProductoSerializer(prod).data
#         return Response(data)


# class ClienteList(APIView):
#     def get(self,request):
#         obj = Cliente.objects.all()
#         data = ClienteSerializer(obj,many=True).data
#         return Response(data)

partido politico/bases/views.py
from re import U
from django import http
from django.db.models.query import RawQuerySet
from django.http import request
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.contrib import messages

from .models import Usuario
from .forms import Userform

class Home(LoginRequiredMixin,TemplateView):
    template_name = 'bases/home.html'
    login_url = 'config:login'

    
class UserList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "bases/users_list.html"
    login_url = 'config:login'
    model = Usuario
    permission_required = 'bases:view_usuario'
    context_object_name = 'obj'

@login_required(login_url='config:login')
@permission_required('bases.change_ususario', login_url='config:home')
def user_admin(request,pk=None):
    template_name = "bases/users_add.html"
    context = {}
    form = None
    obj = None

    if request.method == "GET":
        if not pk:
            form = Userform(instance = None )
        else:
            obj = Usuario.objects.filter(id=pk).first()
            form = Userform(instance = obj)
        context["form"] = form
        context["obj"] = obj

        grupos_usuarios = None
        grupos = None
        if obj:
            grupos_usuarios = obj.groups.all()
            grupos = Group.objects.filter(~Q(id__in=obj.groups.values('id')))
        
        context["grupos_usuario"]=grupos_usuarios
        context["grupos"]=grupos
    
    if request.method == "POST":
        data = request.POST
        e = data.get("email")
        fn = data.get("first_name")
        ln = data.get("last_name")
        p = data.get("password")

        if pk:
            obj = Usuario.objects.filter(id=pk).first()
            if not obj:
                print("Error Usuario No Existe")
            else:
                obj.email = e
                obj.first_name = fn
                obj.last_name = ln
                obj.password = make_password(p)
                obj.save()
        else:
            obj = Usuario.objects.create_user(
                email = e,
                password = p,
                first_name = fn,
                last_name = ln
            )
            print(obj.email,obj.password)
        return redirect('config:users_list')
    
    return render(request,template_name,context)


class UserGroupList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "bases/users_group_list.html"
    login_url = 'config:login'
    model = Group
    permission_required = 'bases:view_usuario'
    context_object_name = 'obj'

@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_groups_admin(request,pk=None):
    template_name = 'bases/users_group_add.html'
    context = {}

    obj = Group.objects.filter(id = pk).first()
    context["obj"] = obj
    permisos = {}
    permisos_grupo = {}
    context["permisos"] = permisos
    context["permisos_grupo"] = permisos_grupo

    if obj:
        permisos_grupo = obj.permissions.all()
        context["permisos_grupo"] = permisos_grupo

        permisos = Permission.objects.filter(~Q(group=obj))
        context["permisos"] = permisos

    # print(permisos)
    # print(permisos_grupo)
    if request.method == "POST":
        name = request.POST.get("name")
        grp = Group.objects.filter(name=name).first()

        if grp and grp.id != pk:
            print("Grupo ya existe, no puede volver a crearlo")
            messages.error(request,"Grupo ya existe, no puede volver a crearlo")
            return redirect("config:user_groups_new")
        
        if not grp and pk != None:
            # Grupo Existe, se está cambiando el Nombre
            grp = Group.objects.filter(id=pk).first()
            grp.name = name
        elif not grp and pk == None:
            grp = Group(name=name)
        else:
            ...
        
        grp.save()
        messages.success(request, "Registro Guardado Satisfactoriamente")
        return redirect("config:user_groups_modify", grp.id)
    return render(request,template_name,context)


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_delete(request,pk):
    if request.method == "POST":
        grp = Group.objects.filter(id=pk).first()

        if not grp:
            print("Grupo No Existe")
        else:
            grp.delete()
        
        messages.success(request,"Registro Borrado Satisfactoriamente")
        return HttpResponse("OK")


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_permission(request,id_grp,id_perm):
    if request.method == "POST":
        grp = Group.objects.filter(id = id_grp).first()

        if not grp:
            messages.error(request,"Grupo No Existe")
            return HttpResponse("Grupo No Existe")
        
        accion = request.POST.get("accion")
        perm = Permission.objects.filter(id=id_perm).first()
        if not perm:
            messages.error(request,"Permiso no existe")
            return HttpResponse("Permiso No Existe")
        
        if accion == "ADD":
            grp.permissions.add(perm)
            messages.success(request,"Permiso Agregado")
        elif accion == "DEL":
            grp.permissions.remove(perm)
            messages.success(request,"Permiso Eliminado")
        else:
            messages.error(request,"Accion no Reconocida")
            return HttpResponse("Accion No Reconocida")

        return HttpResponse("OK")
    return Http404("Método no Reconocido")


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_add(request,id_usr,id_grp):
    if request.method == "POST":
        usr =Usuario.objects.filter(id=id_usr).first()
        if not usr:
            return HttpResponse("Usuario NO Existe")
        
        accion = request.POST.get("accion")
        grp = Group.objects.filter(id=id_grp).first()

        if not grp:
            return HttpResponse("Grupo No Existe")
        
        if accion=="ADD":
            usr.groups.add(grp)
        elif accion=="DEL":
            usr.groups.remove(grp)
        else:
            return HttpResponse("Acción no Reconocida")
        
        return HttpResponse("OK")
    
    return HttpResponse("Error Método no Reconocido")

partido politico/inv/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from .forms import FichaInscripcionForm
from .apis_net_pe import ApisNetPe
from .models import FichaInscripcion

def inscripcion(request):
    if request.method == 'POST':
        form = FichaInscripcionForm(request.POST)
        if form.is_valid():
            ficha = form.save()
            messages.success(request, f'Inscripción exitosa para {ficha.nombres} {ficha.apellido_paterno}')
            return redirect('inv:lista_inscritos')
        else:
            messages.error(request, 'Por favor, corrige los errores en el formulario.')
    else:
        form = FichaInscripcionForm()
    return render(request, 'inv/inscripcion.html', {'form': form})

def get_person_data(request):
    if request.method == 'GET':
        dni = request.GET.get('dni', '')
        api_client = ApisNetPe()
        result = api_client.get_person(dni)
        if result:
            return JsonResponse({
                'nombres': result.get('nombres', ''),
                'apellido_paterno': result.get('apellidoPaterno', ''),
                'apellido_materno': result.get('apellidoMaterno', ''),
                'fecha_nacimiento': result.get('fechaNacimiento', ''),
            })
        else:
            return JsonResponse({'error': 'No se encontraron datos para el DNI proporcionado'}, status=404)
    return JsonResponse({'error': 'Método no permitido'}, status=405)

# def inscripcion_exitosa(request):
#     return render(request, 'inv/inscripcion_exitosa.html')

def lista_inscritos(request):
    inscritos = FichaInscripcion.objects.all().order_by('-fecha_inscripcion')
    return render(request, 'inv/lista_inscritos.html', {'inscritos': inscritos})

class BaseView(LoginRequiredMixin, PermissionRequiredMixin):
    login_url = 'bases:login'
    
    def handle_no_permission(self):
        messages.error(self.request , "No tienes permiso para acceder a esta página.")
        return redirect('config:home')

partido politico/templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sistema de Inscripción de Simpatizantes</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
   <!-- DataTables -->
   <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/custom.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Inicio</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contacto</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-users-cog"></i>
        </a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a href="#" class="nav-link" id="btnLogout">
          <i class="fas fa-sign-out-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% block main_sidebar %}
  <aside class="main-sidebar sidebar-navy elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Sistema de Inscripción</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Inscritos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'inv:inscripcion'%}" class="nav-link">
                  <i class="nav-icon fas fa-user-plus"></i>
                  <p>Nueva Inscripción</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'inv:lista_inscritos'%}" class="nav-link">
                  <i class="nav-icon fas fa-list"></i>
                  <p>Lista de Inscritos</p>
                </a>
              </li>
            </ul>
          </li>
          <!-- Puedes agregar más opciones relacionadas con la gestión de inscritos aquí -->
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
 {% endblock main_sidebar %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      {% block content_wrapper%}
    
      {% endblock content_wrapper %}
      <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
          {% block content %}
        <!-- Aquí va el contenido principal de tu página -->
        {% endblock content %}
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  {% block control_sidebar %}
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Administración de Usuarios</h5>
      <p> <a href="{% url 'config:users_list'%}" rel="noopener noreferrer"><i class="fas fa-user-lock"></i> Usuarios</a> </p>
      <p> <a href="{% url 'config:user_groups_list'%}" rel="noopener noreferrer"><i class="fas fa-users"></i> Grupos</a> </p>
    </div>
  </aside>
  {% endblock control_sidebar %}
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  {% block footer %}
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Sistema de Inscripción de Simpatizantes
    </div>
  </footer>
  {% endblock footer %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- Toastr -->
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<script>
  // Tu código JavaScript aquí
  // (El mismo que tenías antes)
</script>

{% block js %}
{% endblock js%}
</body>
</html>